#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use LogAgent\Command\AgentRunCommand;
use LogAgent\Application;

$application = new Application();
$application->add(new AgentRunCommand);
$application->run();
